# Generated by Django 3.2 on 2022-02-09 07:10

from django.conf import settings
from django.db import migrations

from geocoder.geocoder_functions import fetch_coordinates


def fetch_restaurants_coordinates(apps, schema_editor):
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    Place = apps.get_model('geocoder', 'Place')

    for restaurant in Restaurant.objects.all().iterator():
        coords = fetch_coordinates(
            settings.GEOCODER_TOKEN,
            restaurant.address
        )
        if coords:
            lon, lat = coords
            Place.objects.get_or_create(
                address=restaurant.address,
                defaults={
                    'latitude': lat,
                    'longitude': lon,
                }
            )


def clear_all_places(apps, schema_editor):
    Place = apps.get_model('geocoder', 'Place')
    Place.objects.all().delete()


def fetch_orders_coordinates(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Place = apps.get_model('geocoder', 'Place')

    for order in Order.objects.all().iterator():
        coords = fetch_coordinates(
            settings.GEOCODER_TOKEN,
            order.address
        )
        if coords:
            lon, lat = coords
            Place.objects.get_or_create(
                address=order.address,
                defaults={
                    'latitude': lat,
                    'longitude': lon,
                }
            )


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            fetch_restaurants_coordinates,
            clear_all_places,
        ),
        migrations.RunPython(
            fetch_orders_coordinates,
            clear_all_places,
        ),
    ]
