# Generated by Django 3.2 on 2022-01-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_processed', 'Не обработан'), ('processed', 'Обработан'), ('done', 'Завершен')], default='not_processed', max_length=14, verbose_name='Статус заказа'),
        ),
    ]
