# Generated by Django 3.2 on 2022-02-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20220203_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='available_restaurants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='foodcartapp.restaurant', verbose_name='Рестораны, которые могут приготовить продукт'),
        ),
    ]
