# Generated by Django 3.2 on 2022-02-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_orderitem_available_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='available_restaurants',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='available_restaurants',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_items', to='foodcartapp.RestaurantMenuItem', verbose_name='Рестораны, которые могут приготовить продукт'),
        ),
    ]
