# Generated by Django 3.2 on 2022-02-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20220204_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='available_restaurants',
        ),
    ]
