# Generated by Django 3.2 on 2022-02-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_remove_orderitem_available_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='available_restaurants',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='foodcartapp.Restaurant', verbose_name='Рестораны, которые могут приготовить продукт'),
        ),
    ]
