# Generated by Django 3.2 on 2022-02-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='available_restaurants',
        ),
    ]
