# Generated by Django 3.2 on 2022-02-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_remove_orderitem_available_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными при получении'), ('card_online', 'Банковской картой на сайте')], db_index=True, max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
